services:
  - type: web
    name: andres-obando-portfolio-static
    runtime: static
    repo: https://github.com/cito515432/andres-obando-portfolio
    branch: main
    buildCommand: npm install --no-audit --no-fund && npm run build
    staticPublishPath: ./out
    autoDeployTrigger: commit
    headers:
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /documents/*
        name: Content-Disposition
        value: attachment
